- name: maintenance
  color: "6BA890"
  description: General repo maintenance / configuration
- name: ci
  color: "E8A4BC"
  description: Changes related to automation
- name: infrastructure
  color: "F4B7F4"
  description: Changes made to project infrastructure
- name: api
  color: "6C9BCF"
  description: Changes to the API app
- name: web
  color: "F4A261"
  description: Changes to the web app
- name: db
  color: "7EC8E3"
  description: Changes to the database package
- name: shared
  color: "C5B4E3"
  description: Changes to the shared package

# PR Sizes
- name: size/XS
  color: "009900"
  description: Denotes a PR that changes 0-9 lines, ignoring generated files.
- name: size/S
  color: "77bb00"
  description: Denotes a PR that changes 10-29 lines, ignoring generated files.
- name: size/M
  color: "eebb00"
  description: Denotes a PR that changes 30-99 lines, ignoring generated files.
- name: size/L
  color: "ee9900"
  description: Denotes a PR that changes 100-499 lines, ignoring generated files.
- name: size/XL
  color: "ee5500"
  description: Denotes a PR that changes 500-999 lines, ignoring generated files.
- name: size/XXL
  color: "ee0000"
  description: Denotes a PR that changes 1000+ lines, ignoring generated files.
